name: Create Pull Request from Dev to Master

on:
  push:
    branches:
      - dev-1

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated Pull Request from dev-1 to master"
          title: "Automated Pull Request from dev-1 to master"
          body: |
            This is an automated pull request from the dev-1 branch to the master branch.
          branch: dev-1
          base: master
